trajectory_dim: 2
dataset_file: /media/qmissinne/Starry/AE4353/AE4353-Datasets-2024/2D_QUAD_HOVER.npz

batchsize_train: 1024
batchsize_val: 4096
shuffle_train: True
shuffle_val: False
num_workers_train_loader: 0
num_workers_val_loader: 0

model_hidden_dims: 120
model_num_layers: 4

epochs: 2
validate_per_steps: 500
lr: 0.001 # to be tuned